Removal of shell calls
noironetworks/python-opflex-agent pull request #663
Opened 2022-08-02 18:08 UTC by christides11

Start of removing shell calls from as_metadata_manager

We want to move from calling shell calls directly as they require elevated permissions. This commit replaces shell calls related to ip commands in as_metadata_manager with equivalent calls from neutron's ip_lib, which handles permissions properly.

2022-08-02 20:50 UTC, tbachman requested changes
Overall, great patch! One note on the commit message: the convention is to limit all lines to less than 80 characters (except the title, which I think is supposed to be 60 or less?). Other than that, LGTM!

2022-08-04 18:35 UTC, sayalinaval approved these changes

2022-08-14 15:33 UTC, irathore approved these changes

2022-08-16 11:11 UTC, tbachman approved these changes

2022-08-16 11:11 UTC, merged

2022-08-16 11:11 UTC, tbachman commented
Please create backports through stable/queens.